#ifndef __MESSAGE_DEFINATIONS__
#define __MESSAGE_DEFINATIONS__

#define MSG_CELL_INFO		100
#define MSG_VISIT_CELL		200
#define MSG_MONSOON_ARRIVED	300
#define MSG_SPAWN_NEW_FROG	400
#define MSG_NEW_FROG_BORN	MSG_SPAWN_NEW_FROG
#define MSG_START_TIMER		500
#define MSG_EXIT		600

#endif
