#ifndef __MESSAGE_DEFINATIONS__
#define __MESSAGE_DEFINATIONS__

#define MSG_CELL_INFO		0
#define MSG_VISIT_CELL		1
#define MSG_MONSOON_ARRIVED	2
#define MSG_SPAWN_NEW_FROG	3
#define MSG_NEW_FROG_BORN	MSG_SPAWN_NEW_FROG
#define MSG_START_TIMER		4
#endif
